name: icu4dart
description: An icu package for Dart.
# version: 1.0.0
# homepage: https://www.example.com
# author: JohnWall2016 <5672618@qq.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
